### ISSUE TITLE
教えていただけないでしょうか

### ISSUE THREAD

**Issue by tetuya0703** [nekop/openshift-sandbox#2]
@nekop 
openshift 3.1をansibleのplaybookから構築しました
docker-registryが正しく動作しなかった為、一度、dc/docker-registry、svc/docker-registry、podを削除して
oadm registry --service-account=registry --config=admin.kubeconfig --mount-host=/var/lib/docker-registry
でdocker-registryを再作成をしたのですが、
--> Creating registry registry ...
    serviceaccount "registry" created
    error: rolebinding "registry-registry-role" already exists
    deploymentconfig "docker-registry" created
    service "docker-registry" created
--> Failed
となり、コマンドがFailになります
原因は error: rolebinding "registry-registry-role" already exists
だとわかっているのですが、registry-registry-roleを削除する方法がわからず、苦慮しています

大変、不躾な質問で恐縮ですが、ご指導をいただけますとさいわいです

**Comment by nekop** [comment]
ここはOpenShiftの質問を受ける場所ではないので stackoverflow などのQ/Aサイトを利用したほうが良いと思います。

http://ja.stackoverflow.com/
